<a href="https://colab.research.google.com/github/hojin99/aitest/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### numpy로 ndarray 배열 합치기

In [ ]:
import numpy as np

a = np.arange(10)
b = np.arange(11,21)

print(a.shape)
print(b.shape)

# 차원 변경 없이 합치기
c = np.hstack([a,b])
print(c)
print(c.shape)
# row 단위로 합치기
d = np.vstack([a,b])
print(d)
print(d.shape)
# column 단위로 합치기
e = np.column_stack([a,b])
print(e)
print(e.shape)

(10,)
(10,)
[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 20]
(20,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19 20]]
(2, 10)
[[ 0 11]
 [ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]
 [ 5 16]
 [ 6 17]
 [ 7 18]
 [ 8 19]
 [ 9 20]]
(10, 2)


### pandas로 csv 데이터 가져와서 내용 확인하기

In [14]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv_data')

print(fish.head())
print('---------------')
print(fish.describe())
print('---------------')
pd.unique(fish['Species'])


  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340
---------------
            Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000
---------------


array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)