<a href="https://colab.research.google.com/github/hojin99/aitest/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 배열 합치기

In [9]:
import numpy as np

a = np.arange(10)
b = np.arange(11,21)

print(a.shape)
print(b.shape)

# 차원 변경 없이 합치기
c = np.hstack([a,b])
print(c)
print(c.shape)
# row 단위로 합치기
d = np.vstack([a,b])
print(d)
print(d.shape)
# column 단위로 합치기
e = np.column_stack([a,b])
print(e)
print(e.shape)

(10,)
(10,)
[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 20]
(20,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19 20]]
(2, 10)
[[ 0 11]
 [ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]
 [ 5 16]
 [ 6 17]
 [ 7 18]
 [ 8 19]
 [ 9 20]]
(10, 2)
